#!/usr/bin/env bash

# Idempotent install script for rai dependencies.
# Assumes "raco" is in the path.

HERE_ABS=$(readlink -f $(dirname $0))
PRJ_DIR=$(basename $HERE_ABS)
PARENT_ABS=$(dirname $HERE_ABS)
DEPS_DIR="${PARENT_ABS}/.${PRJ_DIR}.deps"
mkdir -p ${DEPS_DIR}
echo ${DEPS_DIR}

cd ${HERE_ABS}

cat <<EOF >with-env.sh
#!/usr/bin/env bash
# Generated by $0
# Set HOME, so user install goes in ${DEPS_DIR}/.racket
# Note that because of linking, the .racket dir cannot go under the rai/ dir.
HOME=${DEPS_DIR}
exec "\$@"
EOF
chmod +x with-env.sh

( . env.sh ; raco pkg install --deps search-auto rsound )
( . env.sh ; cd ${PARENT_ABS} ; raco pkg install --link rai )

exit 0
