#!/bin/sh

# FIXME: Re-organize this, it has gotten too complicated.
# 
# The racket package should not have any dependencies and only contain
# the compiler.  Next to that there should be a C package that can
# compile the files, probably on top of uc_tools.




# 1. Allow override RACKET_DIR
if [ ! -z "$RACKET_DIR" ]; then
    echo "using RACKET_DIR=$RACKET_DIR"
    RACKET=$RACKET_DIR/bin/racket
fi

# 2. Otherwise git it from path
[ -z "$RACKET" ] && RACKET=$(which racket)

[ -z "$RACKET" ] && echo "Can't locate racket" && exit 1

echo "racket is $(readlink -f $(which $RACKET))"
$RACKET --version

# 3. Assume raco is next to it
RACO=$(dirname $RACKET)/raco

# 4. Where to put deps?

[ -z "$RACKET_DIR" ] && RACKET_DIR=$(dirname $(dirname $RACKET))
echo "RACKET_DIR=$RACKET_DIR"

HERE_ABS=$(readlink -f $(dirname $0))
PARENT_ABS=$(dirname $HERE_ABS)
PRJ_DIR=$(basename $HERE_ABS)

echo "rai is in $HERE_ABS"

# FIXME: special cased.  Find a way to configure this.
if [ "/home/tom/.nix-profile" == $RACKET_DIR ]; then

    DEPS_DIR="${PARENT_ABS}/.${PRJ_DIR}.deps"
    echo "installing deps in $DEPS_DIR"
    mkdir -p ${DEPS_DIR}

cat <<EOF >with-env.sh
#!/bin/sh
# Generated by $0
# Set HOME, so user install goes in ${DEPS_DIR}/.racket
# Note that because of linking, the .racket dir cannot go under the rai/ dir.
HOME=${DEPS_DIR}
export PATH=${RACKET_DIR}/bin:\$PATH
racket --version >&2
exec "\$@"
EOF

else

cat <<EOF >with-env.sh
#!/bin/sh
export PATH=${RACKET_DIR}/bin:\$PATH
racket --version >&2
exec "\$@"
EOF

fi

cd ${HERE_ABS}

chmod +x with-env.sh
echo "generated:"
echo
cat with-env.sh

echo


echo "installing deps"

# if [ ! -z "$SCOPE_DIR" ]; then
#     RACO="$RACO --scope-dir $SCOPE_DIR"
# fi

# ( ./with-env.sh $RACO pkg install --deps search-auto rsound )
( cd ${PARENT_ABS} ; ./${PRJ_DIR}/with-env.sh  $RACO pkg install --link rai )



exit 0
