# RAI top level Makefile
.PHONY: all build clean remove github link

# A note on configuration.
# All commands go through this script:
WITH_ENV := $(shell readlink -f ./with-env.sh)

# Which is added as a dependency to the toplevel rule that builds src
# and test directories.
all: $(WITH_ENV)
	$(WITH_ENV) racket --version
# FIXME: Remove these hardcoded paths.  If this breaks, run ./install-env.sh
#	[ -d ../.rai.deps/.racket/6.8/pkgs/rsound ]
#	[ -d ../.rai.deps/.racket/6.8/pkgs/portaudio ]
	make -C src
	make -C test
	@cat README.md | grep 'white rabbit'

# The configuration is generated by this script:
$(WITH_ENV):
	./install-env.sh

clean:
	make -C test clean
	make -C src clean
	rm -rf `find -name compiled`


# Clean up below this line.

# remove:
# 	$(RACO) pkg remove rai || echo not installed

# github: remove
# 	$(RACO) pkg install github://github.com/zwizwa/rai/master


# link: remove
# 	cd $$(readlink -f .)/.. ; $(RACO) pkg install --link rai

# deps:
# 	$(RACO) pkg install rsound

